SELECT 
	TIMESTAMP
	, CAST(TIMESTAMP AS DATE) AS LOAD_DATE
	, CAST(TIMESTAMP AS TIME) AS LOAD_TIME
	, TRY_CONVERT(FLOAT, GPSNORTHING) AS GPSNORTHING
	, TRY_CONVERT(FLOAT, GPSEASTING) AS GPSEASTING
	, TRY_CONVERT(FLOAT, GPSELEVATION) AS GPSELEVATION
	, TRY_CONVERT(FLOAT, FUEL_RATE) AS FUEL_RATE
	, STATUS
	, TRY_CONVERT(FLOAT, PAYLOAD) AS PAYLOAD
	, TRUCK_ID
	, TRUCK_TYPE_ID
	, SHOVEL_ID
	, DUMP_ID
	, RND
INTO data_group0_converted
 FROM [Teck].[dbo].[data_group0]